[build]
builder = "dockerfile"
dockerfilePath = "web_app/Dockerfile"

[deploy]
startCommand = "cd web_app && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
REDIS_URL = "${{Redis.REDIS_URL}}"
CELERY_BROKER_URL = "${{Redis.REDIS_URL}}"
CELERY_RESULT_BACKEND = "${{Redis.REDIS_URL}}"